---
name: Devel-Cover-Report-Clover
version: 0.10
author:
  - 'David Bartle <captindave@gmail.com>'
abstract: Backend for Clover reporting of coverage statistics
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Devel::Cover: 0
  Template: 0
build_requires:
  Test::MockObject: 0
  Test::MockTime: 0
  Test::More: 0
provides:
  Devel::Cover::Report::Clover:
    file: lib/Devel/Cover/Report/Clover.pm
    version: 0.10
  Devel::Cover::Report::Clover::Builder:
    file: lib/Devel/Cover/Report/Clover/Builder.pm
  Devel::Cover::Report::Clover::Class:
    file: lib/Devel/Cover/Report/Clover/Class.pm
  Devel::Cover::Report::Clover::File:
    file: lib/Devel/Cover/Report/Clover/File.pm
  Devel::Cover::Report::Clover::FileFragment:
    file: lib/Devel/Cover/Report/Clover/File.pm
  Devel::Cover::Report::Clover::FileRegistry:
    file: lib/Devel/Cover/Report/Clover/FileRegistry.pm
  Devel::Cover::Report::Clover::Package:
    file: lib/Devel/Cover/Report/Clover/Package.pm
  Devel::Cover::Report::Clover::PackageFile:
    file: lib/Devel/Cover/Report/Clover/Package.pm
  Devel::Cover::Report::Clover::Project:
    file: lib/Devel/Cover/Report/Clover/Project.pm
  Devel::Cover::Report::Clover::Reportable:
    file: lib/Devel/Cover/Report/Clover/Reportable.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
