---
abstract: 'Backend for Clover reporting of coverage statistics'
author:
  - 'David Bartle <captindave@gmail.com>'
build_requires:
  Devel::Cover: 0
  TAP::Harness: 0
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Cover-Report-Clover
no_index:
  directory:
    - cover_db_test
    - t
provides:
  Devel::Cover::Report::Clover:
    file: lib/Devel/Cover/Report/Clover.pm
    version: 0.33
  Devel::Cover::Report::Clover::Builder:
    file: lib/Devel/Cover/Report/Clover/Builder.pm
  Devel::Cover::Report::Clover::Class:
    file: lib/Devel/Cover/Report/Clover/Class.pm
  Devel::Cover::Report::Clover::File:
    file: lib/Devel/Cover/Report/Clover/File.pm
  Devel::Cover::Report::Clover::FileFragment:
    file: lib/Devel/Cover/Report/Clover/File.pm
  Devel::Cover::Report::Clover::FileRegistry:
    file: lib/Devel/Cover/Report/Clover/FileRegistry.pm
  Devel::Cover::Report::Clover::Package:
    file: lib/Devel/Cover/Report/Clover/Package.pm
  Devel::Cover::Report::Clover::PackageFile:
    file: lib/Devel/Cover/Report/Clover/Package.pm
  Devel::Cover::Report::Clover::Project:
    file: lib/Devel/Cover/Report/Clover/Project.pm
  Devel::Cover::Report::Clover::Reportable:
    file: lib/Devel/Cover/Report/Clover/Reportable.pm
recommends:
  Test::MockTime: 0
requires:
  Class::Accessor: 0
  Devel::Cover: 0
  HTML::Parser: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.33
